import type { Locale } from '@/i18n/config'

export const ui = {
  en: {
    work: 'Work',
    practice: 'Practice',
    lab: 'Lab',
    about: 'About',
    contact: 'Contact',
    experience: 'Experience',
    system: 'System',
    role: 'Role',
    context: 'Context',
    question: 'The question',
    credits: 'Credits',
    whatChanged: 'What changed',
    caseStudy: 'Case study',
    premise: 'Premise',
    encounter: 'Encounter',
    architecture: 'Architecture',
    consequence: 'Consequence',
    media: 'Media',
    movingImage: 'Moving image',
    projectFacts: 'Project facts',
    attribution: 'Attribution',
    authorship: 'Authorship',
    studio: 'Studio',
    client: 'Client',
    year: 'Year',
    location: 'Location',
    collaborators: 'Collaborators',
    authoredWork: 'Authored work',
    collaborativeWork: 'Collaborative work',
    contributionWork: 'Professional contribution',
    experimentalWork: 'Experiment',
    sourceContext: 'Context',
    exactRole: 'My role',
    resultingWork: 'The work',
    knownModules: 'Known media & modules',
    systemMap: 'Relationship map',
    backToWork: 'Back to Work',
    nextCase: 'Next case',
    viewNextCase: 'View next case',
    visitProject: 'Visit project',
    featured: 'Selected',
    contributions: 'Selected professional contributions',
    filters: {
      all: 'All',
      authored: 'Authored',
      systems: 'Systems',
      interactive: 'Interactive',
      immersive: 'Immersive',
      software: 'Software',
      experiments: 'Experiments',
    },
    occupancyOne: 'one other person in the room',
    occupancyMany: 'people in the room',
    rememberHint: 'Hold to remember',
    visit: 'Visit',
    send: 'Send',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    sending: 'Sending…',
    sent: 'Received. I will write back.',
    sendError: 'Something went wrong. Write me directly.',
  },
  fr: {
    work: 'Œuvre',
    practice: 'Pratique',
    lab: 'Labo',
    about: 'À propos',
    contact: 'Contact',
    experience: 'Expérience',
    system: 'Système',
    role: 'Rôle',
    context: 'Contexte',
    question: 'La question',
    credits: 'Crédits',
    whatChanged: 'Ce qui a changé',
    caseStudy: 'Étude de cas',
    premise: 'Prémisse',
    encounter: 'Rencontre',
    architecture: 'Architecture',
    consequence: 'Conséquence',
    media: 'Médias',
    movingImage: 'Image en mouvement',
    projectFacts: 'Repères du projet',
    attribution: 'Attribution',
    authorship: 'Statut d’auteur',
    studio: 'Studio',
    client: 'Client',
    year: 'Année',
    location: 'Lieu',
    collaborators: 'Collaborateurs',
    authoredWork: 'Œuvre d’auteur',
    collaborativeWork: 'Œuvre collaborative',
    contributionWork: 'Contribution professionnelle',
    experimentalWork: 'Expérience',
    sourceContext: 'Contexte',
    exactRole: 'Mon rôle',
    resultingWork: 'L’œuvre',
    knownModules: 'Médias et modules connus',
    systemMap: 'Carte des relations',
    backToWork: 'Retour aux œuvres',
    nextCase: 'Étude suivante',
    viewNextCase: 'Voir l’étude suivante',
    visitProject: 'Visiter le projet',
    featured: 'Choix',
    contributions: 'Contributions professionnelles choisies',
    filters: {
      all: 'Tout',
      authored: 'Auteur',
      systems: 'Systèmes',
      interactive: 'Interactif',
      immersive: 'Immersif',
      software: 'Logiciel',
      experiments: 'Expériences',
    },
    occupancyOne: 'une autre personne dans la pièce',
    occupancyMany: 'personnes dans la pièce',
    rememberHint: 'Maintenir pour retenir',
    visit: 'Visiter',
    send: 'Envoyer',
    name: 'Nom',
    email: 'Courriel',
    message: 'Message',
    sending: 'Envoi…',
    sent: 'Reçu. Je vous écrirai.',
    sendError: 'Un problème est survenu. Écrivez-moi directement.',
  },
} satisfies Record<Locale, Record<string, unknown>>

export function t(locale: Locale) {
  return ui[locale]
}
