import type { Locale } from '@/i18n/config'

export const ui = {
  en: {
    work: 'Work',
    practice: 'Practice',
    lab: 'Lab',
    about: 'About',
    contact: 'Contact',
    experience: 'Experience',
    system: 'System',
    role: 'Role',
    context: 'Context',
    question: 'The question',
    credits: 'Credits',
    whatChanged: 'What changed',
    featured: 'Selected',
    contributions: 'Selected professional contributions',
    filters: {
      all: 'All',
      authored: 'Authored',
      systems: 'Systems',
      interactive: 'Interactive',
      immersive: 'Immersive',
      software: 'Software',
      experiments: 'Experiments',
    },
    occupancyOne: 'one other person in the room',
    occupancyMany: 'people in the room',
    rememberHint: 'Hold to remember',
    visit: 'Visit',
    send: 'Send',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    sending: 'Sending…',
    sent: 'Received. I will write back.',
  },
  fr: {
    work: 'Œuvre',
    practice: 'Pratique',
    lab: 'Labo',
    about: 'À propos',
    contact: 'Contact',
    experience: 'Expérience',
    system: 'Système',
    role: 'Rôle',
    context: 'Contexte',
    question: 'La question',
    credits: 'Crédits',
    whatChanged: 'Ce qui a changé',
    featured: 'Choix',
    contributions: 'Contributions professionnelles choisies',
    filters: {
      all: 'Tout',
      authored: 'Auteur',
      systems: 'Systèmes',
      interactive: 'Interactif',
      immersive: 'Immersif',
      software: 'Logiciel',
      experiments: 'Expériences',
    },
    occupancyOne: 'une autre personne dans la pièce',
    occupancyMany: 'personnes dans la pièce',
    rememberHint: 'Maintenir pour retenir',
    visit: 'Visiter',
    send: 'Envoyer',
    name: 'Nom',
    email: 'Courriel',
    message: 'Message',
    sending: 'Envoi…',
    sent: 'Reçu. Je vous écrirai.',
  },
} satisfies Record<Locale, Record<string, unknown>>

export function t(locale: Locale) {
  return ui[locale]
}
